name: Security

on:
    push:
        branches: [ main ]
    pull_request: ~
    release:
        types: [ created ]
    schedule:
      # Do not make it the first of the month and/or midnight since it is a very busy time
          - cron: "* 10 5 * *"

# See https://stackoverflow.com/a/72408109
concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    security:
        runs-on: ubuntu-latest
        name: Check Dependencies
        strategy:
          fail-fast: false
          matrix:
              php-versions: ['8.1', '8.2']
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: Cache the vulnerability database
                uses: actions/cache@v4
                id: cache-db
                with:
                    path: ~/.symfony/cache
                    key: db

            -   name: Get composer cache directory
                id: composercache
                run: echo "name=dir::$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            
            -   name: Cache composer dependencies
                uses: actions/cache@v4
                with:
                  path: ${{ steps.composercache.outputs.dir }}
                  # Use composer.json for key, if composer.lock is not committed.
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-
            
            -   name: Install Composer dependencies
                uses: php-actions/composer@v6
                with:
                    dev: no
                    args: --no-progress --prefer-dist --optimize-autoloader
    
            -   name: Checks dependencies for known vulnerabilities
                uses: symfonycorp/security-checker-action@v5
